security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            json_login:
                check_path: /login
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
        secured_area:
            pattern:    ^/
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/products/new, roles: ROLE_ADMIN }
        - { path: ^/products/edit/, roles: ROLE_ADMIN }
        - { path: ^/products/delete/, roles: ROLE_ADMIN }
        - { path: ^/products/disabled, roles: ROLE_ADMIN }
        - { path: ^/products/disable/, roles: ROLE_ADMIN }
        - { path: ^/order/edit/, roles: ROLE_ADMIN }
        - { path: ^/order/findAll, roles: ROLE_ADMIN }
        - { path: ^/order/active, roles: ROLE_ADMIN }
        - { path: ^/order/disabled, roles: ROLE_ADMIN }
        - { path: ^/order/disable, roles: ROLE_ADMIN }
        - { path: ^/order/paid, roles: ROLE_ADMIN }
        - { path: ^/order/editPaidPurchase, roles: ROLE_ADMIN }
        - { path: ^/user/editRoles/, roles: ROLE_ADMIN }
        - { path: ^/user/active, roles: ROLE_ADMIN }
        - { path: ^/user/disabled, roles: ROLE_ADMIN }
        - { path: ^/user/disable, roles: ROLE_ADMIN }
        - { path: ^/user/findAll, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
